### ISSUE TITLE
Cloning the Repo and follwoing the README steps but still no record is being done.

### ISSUE THREAD

**Issue by Crazycoder122** [keploy/samples-typescript#6]
Cloning the Repo and follwoing the README steps but still no record is being done.

**Comment by Sonichigo** [comment]
@Crazycoder122 can you please share the ss of what happen after you try ``export KEPLOY_MODE=record``, also on what OS platform you are using application ?

**Comment by Crazycoder122** [comment]
Couldn't share the ss cz there is nothing special..
Only the prompt "App running at..." is appearing.

On the other hand no "keploy_tests" folder is not being generated.
Hence `export KEPLOY_MODE=record` throws an error.

**Comment by Sonichigo** [comment]
@Crazycoder122 can you tell which OS platform you are using ?

**Comment by Crazycoder122** [comment]
> @Crazycoder122 can you tell which OS platform you are using ?

Windows.

**Comment by Sonichigo** [comment]
> > @Crazycoder122 can you tell which OS platform you are using ?
> 
> Windows.

``export`` command isn't compatible with CMD and Powershell, that's why testcases is not getting recorded. Try the command in GitBash Terminal .
